### ISSUE TITLE
service: fails to decode URL encoding correctly

### ISSUE THREAD

**Issue by petrrr** [EIDA/wfcatalog#11]
Apparently the service does not decode URL encoded escape sequences (starting with `%`) correctly.

Here some evidence.

This one works:
* http://webservices.ingv.it/eidaws/wfcatalog/1/query?starttime=2018-01-01T00:00:00.000&endtime=2018-12-31T00:00:00.000

This one should be equivalent, but fails:
* http://webservices.ingv.it/eidaws/wfcatalog/1/query?starttime=2018-01-01T00%3A00%3A00.000&endtime=2018-12-31T00%3A00%3A00.000

```
Error 400: Bad Request
The submitted query string is invalid
Usage details are available from /documentation/
Request:
/wfcatalog/1/query?starttime=2018-01-01T00%3A00%3A00.000&endtime=2018-12-31T00%3A00%3A00.000
Request Submitted:
Mon Oct 01 2018 21:16:22 GMT+0000 (UTC)
Service Version:
1.0.0
```

This is particularly relevant because some frameworks escape characters with special meaning.

**Comment by Jollyfant** [comment]
Hi Petr, this has been fixed in https://github.com/EIDA/wfcatalog/commit/a5d4ce5fc125862b591d09ccd9c9730012eb729c. You can apply the single line change to your service.
