### ISSUE TITLE
Declaration of metrics parameters with comparison extensions in the wadl

### ISSUE THREAD

**Issue by kaestli** [EIDA/wfcatalog#14]
the current version of the wadl (https://github.com/EIDA/wfcatalog/blob/master/service/application.wadl) declares the plain mecis parameters, but not their corresponding parameters with comparison suffixes: ..._eq, ..._ne, ..._gt, ..._ge, ..._lt, ..._le . While this may be good enough for a human interpreter aware of the service specification document (http://www.orfeus-eu.org/documents/WFCatalog_Specification-v0.22.pdf, especially page 8), an automatic routine generating a client stub based on the WADL standard would fail to catch this part of the service's functionality.

**Comment by Jollyfant** [comment]
Hi Philip, this was lazy by me. I didn't want to write down all of the 200 flag, suffix combinations. It shouldn't be too hard to generate the WADL with a script. @jbienkowski
