### ISSUE TITLE
Enabling HTTPS for wfcatalog?

### ISSUE THREAD

**Issue by jan-michalek** [EIDA/wfcatalog#28]
I initially thought that enabling HTTPS for the service is only server configuration. Can anyone provide insight what needs to be changed to allow HTTPS for wfcatalog? I didn't make any changes to FDSN STATION or DATASELECT after enabling HTTPS and those both work. Not wfcatalog (availabiliy, metrics).

**Comment by jschaeff** [comment]
we make https through our reverse proxy (haproxy) and it just works :

https://ws.resif.fr/eidaws/wfcatalog/1/

I would recommend not touching the webservice itself but configure the
revers proxy (httpd, nginx, haproxy, ...)

**Comment by jan-michalek** [comment]
Indeed, our wfcatalog is also working over HTTPS (using revers proxy). The web tools (availability, metrics) for wfcatalog were not working due to hardwired URL. Fixed.
