### ISSUE TITLE
Webserver crash when `include=all`

### ISSUE THREAD

**Issue by jschaeff** [EIDA/wfcatalog#32]
When a request comes with parameter `include=all` the server responds a 502.

Logs from server: 

```
isValidRegex: Unknown type for key include
/app/server.js:1058
          short_record_read: doc["io_flags"]["srr"],
                                            ^

TypeError: Cannot read properties of undefined (reading 'srr')
    at setClientKeys (/app/server.js:1058:45)
    at processDailyStream (/app/server.js:720:25)
    at /app/node_modules/mongodb/lib/utils.js:349:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

As a matter of fact, I don't have any document with `short_record_read`

From the collector code, I can see https://github.com/EIDA/wfcatalog/blob/master/collector/WFCatalogCollector.py#L1086

I'm not sure why this information is not in my wfcatalog database ... Any hints ?

**Comment by jbienkowski** [comment]
Fixed with #33.
