### ISSUE TITLE
package.json points to wrong repo

### ISSUE THREAD

**Issue by petrrr** [EIDA/wfcatalog#5]
I think the `package.json` file still point to the private repo https://github.com/Jollyfant/EIDAWS, is outdated wrt. to the EIDA repo:

* https://github.com/EIDA/wfcatalog/blob/master/service/package.json#L18
* https://github.com/EIDA/wfcatalog/blob/master/service/package.json#L29

@Jollyfant: Consider removing the old repo, so that the procedure errors out instead of installing an outdated version.

**Comment by Jollyfant** [comment]
Woops, thanks! I'll fix this asap.
