### ISSUE TITLE
multiple collectors in parallel (same db)

### ISSUE THREAD

**Issue by megies** [EIDA/wfcatalog#8]
This is kind of a dumb question, since after all it *is* a database.. but just to be sure: Is it safe to run multiple collector jobs in parallel (running on different directories), writing to the same mongo db?

**Comment by Jollyfant** [comment]
Yes that is fine. In the repo there is a script that can do multithreading and spread the workload across multiple processes automatically. Alternatively you can start multiple Collector processes, e.g. one for each year.

**Comment by megies** [comment]
OK, thanks for the feedback!
