### ISSUE TITLE
Problems with service tests

### ISSUE THREAD

**Issue by megies** [EIDA/wfcatalog#9]
@Jollyfant I'm currently trying to get the service up and running, but `npm test` throws an exception:

```
sysop:~/wfcatalog/service$ npm test

> EIDA-NG-WFCatalog@1.3.0 test /home/sysop/wfcatalog/service
> node runtests.js

[ERROR-Server:30149] 1502373012210 [1] failed to authenticate against server 127.0.0.1:27017 { type: 'error',
  message: '[1] failed to authenticate against server 127.0.0.1:27017',
  className: 'Server',
  pid: 30149,
  date: 1502373012210 }

/home/sysop/wfcatalog/service/node_modules/mongodb/lib/mongo_client.js:398
              throw err
              ^
FATAL: The connection to the database could not be established.
npm ERR! Test failed.  See above for more details.
```
Installation of the service seemed to be OK:
```
sysop:~/wfcatalog/service$ npm install
npm WARN deprecated mongodb@2.1.21: Please upgrade to 2.2.19 or higher

> dtrace-provider@0.8.5 install /home/sysop/wfcatalog/service/node_modules/dtrace-provider
> node scripts/install.js

EIDA-NG-WFCatalog@1.3.0 /home/sysop/wfcatalog/service
├─┬ bunyan@1.8.12 
│ ├─┬ dtrace-provider@0.8.5 
│ │ └── nan@2.6.2 
│ ├── moment@2.18.1 
│ ├─┬ mv@2.1.1 
│ │ ├─┬ mkdirp@0.5.1 
│ │ │ └── minimist@0.0.8 
│ │ ├── ncp@2.0.0 
│ │ └─┬ rimraf@2.4.5 
│ │   └─┬ glob@6.0.4 
│ │     ├─┬ inflight@1.0.6 
│ │     │ └── wrappy@1.0.2 
│ │     ├─┬ minimatch@3.0.4 
│ │     │ └─┬ brace-expansion@1.1.8 
│ │     │   ├── balanced-match@1.0.0 
│ │     │   └── concat-map@0.0.1 
│ │     ├── once@1.4.0 
│ │     └── path-is-absolute@1.0.1 
│ └── safe-json-stringify@1.0.4 
├─┬ express@4.13.4 
│ ├─┬ accepts@1.2.13 
│ │ ├─┬ mime-types@2.1.16 
│ │ │ └── mime-db@1.29.0 
│ │ └── negotiator@0.5.3 
│ ├── array-flatten@1.1.1 
│ ├── content-disposition@0.5.1 
│ ├── content-type@1.0.2 
│ ├── cookie@0.1.5 
│ ├── cookie-signature@1.0.6 
│ ├─┬ debug@2.2.0 
│ │ └── ms@0.7.1 
│ ├── depd@1.1.1 
│ ├── escape-html@1.0.3 
│ ├── etag@1.7.0 
│ ├─┬ finalhandler@0.4.1 
│ │ └── unpipe@1.0.0 
│ ├── fresh@0.3.0 
│ ├── merge-descriptors@1.0.1 
│ ├── methods@1.1.2 
│ ├─┬ on-finished@2.3.0 
│ │ └── ee-first@1.1.1 
│ ├── parseurl@1.3.1 
│ ├── path-to-regexp@0.1.7 
│ ├─┬ proxy-addr@1.0.10 
│ │ ├── forwarded@0.1.0 
│ │ └── ipaddr.js@1.0.5 
│ ├── qs@4.0.0 
│ ├── range-parser@1.0.3 
│ ├─┬ send@0.13.1 
│ │ ├── destroy@1.0.4 
│ │ ├── http-errors@1.3.1 
│ │ ├── mime@1.3.4 
│ │ └── statuses@1.2.1 
│ ├─┬ serve-static@1.10.3 
│ │ └── send@0.13.2 
│ ├─┬ type-is@1.6.15 
│ │ └── media-typer@0.3.0 
│ ├── utils-merge@1.0.0 
│ └── vary@1.0.1 
└─┬ mongodb@2.1.21 
  ├── es6-promise@3.0.2 
  ├─┬ mongodb-core@1.3.21 
  │ ├── bson@0.4.23 
  │ └─┬ require_optional@1.0.1 
  │   ├── resolve-from@2.0.0 
  │   └── semver@5.4.1 
  └─┬ readable-stream@1.0.31 
    ├── core-util-is@1.0.2 
    ├── inherits@2.0.3 
    ├── isarray@0.0.1 
    └── string_decoder@0.10.31 

npm WARN EIDA-NG-WFCatalog@1.3.0 license should be a valid SPDX license expression
```

I'm running the mongodb of Debian Jessie installed via system packages (version 1:2.4.10-5+deb8u1) and can connect with the credentials (I also put them into the `configuration.json` of the service) just fine:

```
$ mongo -u XXX -p XXX localhost:27017/wfrepo
MongoDB shell version: 2.4.10
connecting to: localhost:27017/wfrepo
> show collections
c_segments
daily_streams
system.indexes
system.users
> 
bye
```
The mongodb log doesn't show anything that hints at a problem (for the `npm test` call), especially not with credentials/authentication:
```
Thu Aug 10 15:50:12.163 [initandlisten] connection accepted from 127.0.0.1:50246 #2 (1 connection now open)
Thu Aug 10 15:50:12.190 [conn2] end connection 127.0.0.1:50246 (0 connections now open)
Thu Aug 10 15:50:12.198 [initandlisten] connection accepted from 127.0.0.1:50247 #3 (1 connection now open)
Thu Aug 10 15:50:12.719 [conn3] end connection 127.0.0.1:50247 (0 connections now open)
```

Any ideas what could be the problem or how to debug this?

CC @jwassermann

**Comment by Jollyfant** [comment]
In `server.js` there is a function called `setMongoAuthentication`. You can insert a log statement there to see if the `CONFIG.MONGO.AUTHHOST` is what it is supposed to be.

Is it like this:

    "AUTHENTICATE": true,
    "HOST": "localhost:27017/wfrepo",
    "USER": "XXX",
    "PASS": "XXX",

**Comment by megies** [comment]
Seems that the ` + '?authMechanism=SCRAM-SHA-1'` bit at the end is making the problems.. from a quick search it looks like this mechanism is pretty new and only in very recent mongo versions.. https://docs.mongodb.com/manual/release-notes/3.0-scram/#upgrade-2-6-mongodb-cr-users-to-scram-sha-1

**Comment by megies** [comment]
`testWADL` is now the only test failure.. there seems to be a hard coded md5 hash in the test routine? Just a wild guess but maybe that value has to be updated (at least the application.wadl I have locally has a different md5sum)?

**Comment by Jollyfant** [comment]
Ok good! About the wadl... yeah that exactly.. 🦆 

Should update it but it can be ignored.

**Comment by megies** [comment]
![screenshot from 2017-08-10 16-44-02](https://user-images.githubusercontent.com/1842780/29176081-27527f50-7deb-11e7-8609-24e8f94216d4.png)

Links on the main page don't reflect the BASE_URL (the `/alpha` is missing in the links..)

**Comment by Jollyfant** [comment]
Ok good point. This will be updated next week with the 1.0.0 release (and we get rid of alpha).

**Comment by megies** [comment]
Aside from that it seems to be running OK in a first local-only test. What's the recommended way to run this service as a system service in background (and automatically restarting when down)?

**Comment by Jollyfant** [comment]
Yeah for a production deployment run it as a systemd service. This is for Fedora but idk about Debian. For `WFCatalog` I have:

    [Unit]
    Description=Wfcatalog service
    After=network.target

    [Service]
    Type=simple
    User=orfeus
    ExecStart=/data/seismo/opt/node/bin/node /data/seismo/wfcatalog/service/wfcatalog.js
    KillMode=control-group
    EnvironmentFile=/home/orfeus/systemdenvironment.ini

    # Enable auto restart of systemd services
    Restart=always
    RestartSec=5s
    StartLimitInterval=80
    StartLimitBurst=3

    # StandardOutput / Error is not configured (parameter logoutputdestination)

    [Install]
    WantedBy=multi-user.target

and don't forget about `MongoDB`:

    [Unit]
    Description=Mongodb service
    After=network.target

    [Service]
    Type=simple
    User=orfeus
    ExecStart=/data/seismo/opt/mongodb/bin/mongod --auth --dbpath /data/mongo/db/ --logpath /data/mongo/log/mongod.log
    KillMode=control-group
    EnvironmentFile=/home/orfeus/systemdenvironment.ini


    # Enable auto restart of systemd services
    Restart=always
    RestartSec=5s
    StartLimitInterval=80
    StartLimitBurst=3

    # StandardOutput / Error is not configured (parameter logoutputdestination)

    [Install]
    WantedBy=multi-user.target

**Comment by Jollyfant** [comment]
@megies what is your `CONFIG.BASE_URL` set as? It should be: `/eidaws/wfcatalog/1/`. I bumped the application version too in the newest commit.

**Comment by Jollyfant** [comment]
https://github.com/EIDA/wfcatalog/commit/908d2d15a72168cca14b0ca3ffea2af0ac7faab5 this commit.

**Comment by megies** [comment]
To me it seems like the above problem of wroing links might be due to `root.html`, no?

**Comment by Jollyfant** [comment]
`root.html` is just a static file that is presented when a request is made to `CONFIG.BASE_URL`.. So `/eidaws/wfcatalog/1/`. This should be OK AFAIK.

**Comment by megies** [comment]
Ah, the problem is the trailing backslash that is expected..

Assuming `BASE_URL` is `/wfcatalog/alpha/` and in the browser you navigate to `.../wfcatalog/alpha/` the links go to e.g. `.../wfcatalog/alpha/query/` but if you navigate to `.../wfcatalog/alpha` (without trailing backslash), then the links go to e.g. `.../wfcatalog/query/`

**Comment by Jollyfant** [comment]
Ok so make sure to add a backslash, is `/eidaws/wfcatalog/1/` good?

**Comment by megies** [comment]
> so make sure to add a backslash

Well, the problem is that you can't control whether users will add the backslash or not. If you don't want to face puzzled users and complaints etc. in the future, I think it should be fixed in the source code..

**Comment by Jollyfant** [comment]
Oh I see the problem now.. I'm adding some middleware to remove trailing slashes.

**Comment by Jollyfant** [comment]
Thanks @megies -- here https://github.com/EIDA/wfcatalog/commit/f6345814058ece581faf9e55f574af866565531a

**Comment by megies** [comment]
@Jollyfant see https://github.com/EIDA/wfcatalog/commit/f6345814058ece581faf9e55f574af866565531a#commitcomment-23598905

**Comment by Jollyfant** [comment]
Hmm good point... can you try again?

**Comment by Jollyfant** [comment]
By the way Tobias, can you write a little bit of information about your institute/EIDA node that I can add to this page. Look at KNMI for an example.

http://ams.orfeus-eu.org/data/eida/nodes/LMU/

**Comment by megies** [comment]
> ExecStart=/data/seismo/opt/node/bin/node /data/seismo/wfcatalog/service/wfcatalog.js

Is there anything special in that `wfcatalog.js` file? Because I don't see it in the repo.. I guess `node server.js` will do?

**Comment by Jollyfant** [comment]
Yeah, for our production deployment I just renamed it to `wfcatalog.js` to make sure I can find it in the haystack. `server.js` is too ambiguous if you run many services :rofl:

**Comment by megies** [comment]
Our service is up, in case you wanna have a look: http://erde.geophysik.uni-muenchen.de/eidaws/wfcatalog/1/

CC @jwassermann

**Comment by Jollyfant** [comment]
It works! But you need to apply some db indices:

    db.daily_streams.createIndex({"ts": 1, "net": 1, "sta": 1})
    db.daily_streams.createIndex({"files.name": 1})
    db.daily_streams.createIndex({"fileId": 1})

    db.c_segments.createIndex({"streamId": 1})


I tried getting some continuous segments and it took about 2 minutes.

**Comment by megies** [comment]
The manual was not entirely clear to me regarding these index operations, i have to admit.. are they supposed to be executed regularly? Manual states that they should be created after inital data processing and i'm still running old data.. ??

**Comment by ltrani** [comment]
You just need to create them once executing those commands in the DB console.

**Comment by megies** [comment]
OK, I ran those commands now.

**Comment by Jollyfant** [comment]
> The manual was not entirely clear to me regarding these index operations, i have to admit.. are they supposed to be executed regularly? Manual states that they should be created after inital data processing and i'm still running old data.. ??

Only because creating the indexation may take long time and will block document from being inserted and thus time out some metrics. I'll test performance tomorrow.

**Comment by megies** [comment]
Didn't take long for me.. and the DB is at 8 GB, I think.

**Comment by Jollyfant** [comment]
LMU only has network BW right? So that is expected.. number of documents in daily_streams & continuous segments would be nice to know. How far are you with processing?

**Comment by Jollyfant** [comment]
Tested a request with csegments and it is much faster now.

**Comment by megies** [comment]
> LMU only has network BW right? So that is expected.. number of documents in daily_streams & continuous segments would be nice to know. How far are you with processing?

Yes, it's mostly `BW`. 2012-now is done, Currently crunching 2010/11.

```
> db.c_segments.count()
2249472
> db.daily_streams.count()
908196
```

**Comment by Jollyfant** [comment]
Thanks! That's interesting. The ratio of your `c_segments` : `daily_streams` is roughly 2.5. For us at ODC the data is a little gappier at a ratio of 80. 😆

**Comment by megies** [comment]
Thanks for the help @Jollyfant!

**Comment by megies** [comment]
Btw., @Jollyfant  I think you can add LMU to this page as "online": http://www.orfeus-eu.org/data/eida/eidaws

**Comment by Jollyfant** [comment]
Added.

**Comment by megies** [comment]
Thanks!
